<?php
namespace EventConnector;

/**
 * Test class for XEvent.
 * Generated by PHPUnit on 2011-12-18 at 18:51:58.
 */
class XEventTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var XEvent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new XEvent('test_sysname', ['test' => 'test_param'], $this);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->object = false;
    }

    /**
     * testSysname().
     */
    public function testSysname()
    {
        $this->assertEquals('test_sysname', $this->object->event_sysname());
    }

    /**
     * testParams().
     */
    public function testParams()
    {
        $params = $this->object->event_params();

        $this->assertTrue(is_array($params));

        $this->assertTrue(isset($params['test']));

        $this->assertTrue($params['test'] === 'test_param');
    }

    public function testEventSetResult()
    {
        $result = ['my' => 'result'];

        $this->object->event_set_result($result);

        $this->assertEquals($result, $this->object->event_result());
    }

    /**
     * testOwner().
     */
    public function testOwner()
    {
        $this->assertTrue(($this === $this->object->event_owner()));
    }
}